### ISSUE TITLE
Is it working? What version of ecal is supported?

### ISSUE THREAD

**Issue by l1va** [Blutkoete/golang-ecal#2]
Hi Tobias, 
Thank you for the go interface!

Are you planing to support the repo?  

Best regards, Mike.

**Comment by Blutkoete** [comment]
Hello!

As the eCAL C interface is dedicated to being ABI stable, this package should work with all recent versions of eCAL, including 5.7.5 (I have it running with 5.7.5 at the moment). Currently, publishing and subscribing is implemented on the Go side and confirmed to be working "on my machine".

I want to get this repo feature complete (e.g. events), but this won't happen before after Christmas as I'm currently under heavy workload in my job which negatively effects my motivation to program in my free time. But as I know now that I'm not the only consumer, I may speed up things a bit.

Of course, if you are a Go/CGo programmer and want to create an interface package yourself and get it feature complete faster, I'll happily drop the name on my repo to avoid confusion and contribute to your repository. 

I'm glad to see someone for whom this might be of use.

**Comment by l1va** [comment]
Thank you for your answer!
On my stage of ideas, the speed is not so important. And for sure I understand your workload, I think every programmer has the same =) 
I am searching for good dds implementations at a little bit higher level than C. Now I'm thinking about using, not developing ( I have a lot of ideas about what to develop and want to skip some stuff if it is possible ), and I am not too skilled in C programming.  
The most important part for me - to understand the API and I think the current state of the repo is enough.
